version: '3'

volumes:
  firebase-node_modules:

services:
  firebase:
    build: .
    image: firebase
    volumes:
      - ./:/app
      - firebase-node_modules:/app/functions/node_modules
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 8080:8080 # Cloud Firestore
      - 9099:9099 # Authentication
    tty: true
    environment:
      - FIREBASE_PROJECT=nc-management
      - FIREBASE_TOKEN=1//0eXr1oKRyl7HACgYIARAAGA4SNwF-L9IrxVu-QbxTSRI25Nr-uDjSq2IjvjqmTx77aZprTS3sV1iUndUWX39ZhjPuSEdNMIteje8
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
      - CHOKIDAR_USEPOLLING=true